project:
  type: website
  output-dir: docs

website:
  title: "Team EV Turkey"
  navbar:
    background: "#003366"
    search: true
    left:
      - text: "Home"
        icon: house
        href: index.qmd
      - text: "Data"
        icon: table
        href: data.qmd
      - text: "Analysis"
        icon: bar-chart
        href: analysis.qmd
    tools:
      - icon: github
        href: https://github.com/emu-hacettepe-analytics/emu430-fall2024-team-team-ev-turkey
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 430 - Fall 2024 | Team EV Turkey"
    border: true

format:
  html:
    toc: true
    toc-title: "İçindekiler"
    toc-location: left
    smooth-scroll: true
    code-fold: true
    code-tools: true
    theme: 
      light: lux 
      dark: slate
    css: styles.css

editor: visual